### ISSUE TITLE
unable to curl without a terminal

### ISSUE THREAD

**Issue by TheSorton** [TheSorton/arisu.py#3]
for some reason, in util.py,
```python
os.system(f'curl -o .img.png {avatarImage}')
```
will not work without a terminal open for some odd reason (which is common for running bots). I am not sure if its an issue with the nature of `os.system` or whatever.

**Comment by h4pZ** [comment]
I think [https://github.com/TheSorton/arisu.py/commit/61f4b66b77977a6a00896f3c5d096e8ec52ef9aa](url) should fix it :)

**Comment by TheSorton** [comment]
fixed. thanks @h4pZ
